### PR TITLE
Feat/train with .csv

### PR DESCRIPTION
**Pull request by ishiko732**
I attempted to train using a .csv file, and the dataset I used is from: https://github.com/open-spaced-repetition/fsrs4anki/issues/450.

image

### CODE REVIEW

**Comment by AlexErrant** [comment]
I approve of this PR's high-level goal, but am gonna hold my nits until I figure out [the `vite build` issue](https://github.com/open-spaced-repetition/fsrs-browser/issues/9).

**Comment by AlexErrant** [comment]
I'll handle the conflicts (tomorrow 😅).

**Comment by ishiko732** [comment]
image
I have found that the latest version does not support training on two consecutive different files, whereas the previous version 0.2.1 did support it.
I have to refresh the page in order to train again.

**Comment by ishiko732** [comment]
> I have found that the latest version does not support training on two consecutive different files, whereas the previous version 0.2.1 did support it. I have to refresh the page in order to train again.

image
I have fixed the issue that was preventing consecutive training.

**Pull request merged**
