### PR TITLE
update burn to v0.13.1, for real this time

### LINKED ISSUE #23: [BUG] Maximum call stack size exceeded
image

The file for reproduction: [revlog_martin.csv](https://github.com/open-spaced-repetition/fsrs-browser/files/15028049/revlog_martin.csv)

### PR DESCRIPTION
**Pull request by AlexErrant**
Closes https://github.com/open-spaced-repetition/fsrs-browser/issues/23

Ties together https://github.com/open-spaced-repetition/fsrs-rs/pull/187 and https://github.com/open-spaced-repetition/burn/pull/4

### CODE REVIEW

**Comment by AlexErrant** [comment]
Confirming that this build can train the `revlog_martin.csv` file

image

**Comment by AlexErrant** [comment]
I'll change this PR to include the fsrs-rs 0.6.2 update tomorrow >_>

**Comment by AlexErrant** [comment]
Actually, I'll upgrade to 0.6.2 later today/tomorrow when I fix https://github.com/open-spaced-repetition/fsrs-browser/issues/22 since that will make changes to fsrs-rs's fsrs-browser branch.

**Comment by L-M-Sherlock** [comment]
> when I fix #22 since that will make changes to fsrs-rs's fsrs-browser branch.

I'm curious about your solution. Do you plan to add a timezone argument for the input? Or a timestamp like `next_day_at` of Anki?

**Pull request merged**
